spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:8090
#  cloud:
#    gateway:
#        routes:
#          - id : r1
#            uri: http://localhost:8083/
#            predicates:
#              - Path=/contributions/**
#          - id: r2
#            uri: http://localhost:8082/
#            predicates:
#              - Path=/group/**
######################### static eureka ##################
#    gateway:
#        routes:
#          - id : r1
#            uri: lb://CONTRIBUTIONSERVICE
#            predicates:
#              - Path=/contributions/**
#          - id: r2
#            uri: lb://GROUPSERVICE
#            predicates:
#              - Path=/group/**
#    discovery:
#      enabled: true
#
#    gateway:
#      discovery:
#        locator:
#          lower-case-service-id: true

#server:
#  port: 8080




