spring:
  application:
    name: GetwayService
  cloud:
    gateway:
        routes:
          - id : r1
            uri: http://localhost:8083/
            predicates:
              - Path=/contributions/**
          - id: r2
            uri: http://localhost:8082/
            predicates:
              - Path=/group/**
    discovery:
      enabled: false

server:
  port: 8080


